import type { NotificationEvent } from '../types/events.types.js';
import type { CreateNotificationOptions } from '../types/notification.types.js';

/**
 * Notification Helper Functions
 *
 * Factory functions for creating common notification types.
 * Pure functions that return valid NotificationEvent objects.
 *
 * Usage in n8n workflows:
 * ```javascript
 * const { createSuccessNotification } = require('./utils/notificationHelpers');
 * const notification = createSuccessNotification(userId, 'Export completed', {
 *   actionUrl: '/exports/12345',
 *   metadata: { exportId: '12345' }
 * });
 * await notificationService.publish(notification);
 * ```
 */

/**
 * Create base notification with defaults
 */
function createNotification(options: CreateNotificationOptions): NotificationEvent {
  const {
    userId,
    title,
    message,
    category = 'info',
    severity = 'normal',
    priority = 'normal',
    actionUrl,
    iconName,
    metadata,
  } = options;

  return {
    type: 'notification',
    id: '', // Will be generated by service if empty
    userId,
    timestamp: new Date().toISOString(),
    category,
    severity,
    priority,
    title,
    message,
    actionUrl,
    iconName,
    data: metadata,
  };
}

/**
 * Create success notification (green)
 *
 * Used for: Successful operations, confirmations
 * Examples: "File uploaded", "Email sent", "Changes saved"
 *
 * @param userId - Target user ID
 * @param message - Success message
 * @param options - Additional options
 */
export function createSuccessNotification(
  userId: string,
  message: string,
  options?: Partial<Omit<CreateNotificationOptions, 'userId' | 'message' | 'category'>>
): NotificationEvent {
  return createNotification({
    userId,
    message,
    category: 'success',
    severity: 'normal',
    iconName: 'CheckCircle',
    ...options,
  });
}

/**
 * Create error notification (red)
 *
 * Used for: Failed operations, errors
 * Examples: "Failed to send email", "Upload failed", "Invalid data"
 *
 * @param userId - Target user ID
 * @param message - Error message
 * @param error - Optional error object (will be logged, not sent to user)
 * @param options - Additional options
 */
export function createErrorNotification(
  userId: string,
  message: string,
  error?: Error | string,
  options?: Partial<Omit<CreateNotificationOptions, 'userId' | 'message' | 'category'>>
): NotificationEvent {
  // Log error for debugging (don't send full error to frontend)
  if (error) {
    console.error('❌ Error notification:', {
      userId,
      message,
      error: error instanceof Error ? error.message : error,
    });
  }

  return createNotification({
    userId,
    message,
    category: 'error',
    severity: 'high',
    priority: 'high',
    iconName: 'AlertCircle',
    ...options,
  });
}

/**
 * Create info notification (blue)
 *
 * Used for: Informational messages, status updates
 * Examples: "Processing started", "New message", "User joined"
 *
 * @param userId - Target user ID
 * @param message - Info message
 * @param options - Additional options
 */
export function createInfoNotification(
  userId: string,
  message: string,
  options?: Partial<Omit<CreateNotificationOptions, 'userId' | 'message' | 'category'>>
): NotificationEvent {
  return createNotification({
    userId,
    message,
    category: 'info',
    severity: 'normal',
    iconName: 'Info',
    ...options,
  });
}

/**
 * Create warning notification (yellow)
 *
 * Used for: Warnings, cautions, non-critical issues
 * Examples: "Quota almost full", "Session expiring soon", "Deprecated feature"
 *
 * @param userId - Target user ID
 * @param message - Warning message
 * @param options - Additional options
 */
export function createWarningNotification(
  userId: string,
  message: string,
  options?: Partial<Omit<CreateNotificationOptions, 'userId' | 'message' | 'category'>>
): NotificationEvent {
  return createNotification({
    userId,
    message,
    category: 'warning',
    severity: 'normal',
    priority: 'normal',
    iconName: 'AlertTriangle',
    ...options,
  });
}

/**
 * Create system notification
 *
 * Used for: System-level events, platform updates
 * Examples: "System maintenance scheduled", "New feature available"
 *
 * @param userId - Target user ID
 * @param message - System message
 * @param options - Additional options
 */
export function createSystemNotification(
  userId: string,
  message: string,
  options?: Partial<Omit<CreateNotificationOptions, 'userId' | 'message' | 'category'>>
): NotificationEvent {
  return createNotification({
    userId,
    message,
    category: 'system',
    severity: 'low',
    iconName: 'Settings',
    ...options,
  });
}

/**
 * Create critical notification (modal-level urgency)
 *
 * Used for: Critical alerts requiring immediate attention
 * Examples: "Security alert", "Payment failed", "Account locked"
 *
 * @param userId - Target user ID
 * @param message - Critical message
 * @param options - Additional options
 */
export function createCriticalNotification(
  userId: string,
  message: string,
  options?: Partial<Omit<CreateNotificationOptions, 'userId' | 'message' | 'category'>>
): NotificationEvent {
  return createNotification({
    userId,
    message,
    category: 'error',
    severity: 'critical',
    priority: 'urgent',
    iconName: 'AlertOctagon',
    ...options,
  });
}
